import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,Play,RotateCcw,Shuffle,BarChart3,BookOpen,Clock3,CheckCircle2,XCircle,Database,Zap,Code2} from 'lucide-react';
import './styles.css';

const algorithms={
 linear:{name:'Linear Search',complexity:'O(n)',space:'O(1)',fn:(a,t)=>{let s=[];for(let i=0;i<a.length;i++){s.push(i);if(a[i]===t)return{i,comparisons:i+1,steps:s}}return{i:-1,comparisons:a.length,steps:s}}},
 binary:{name:'Binary Search',complexity:'O(log n)',space:'O(1)',fn:(a,t)=>{let l=0,r=a.length-1,s=[];while(l<=r){let m=Math.floor((l+r)/2);s.push(m);if(a[m]===t)return{i:m,comparisons:s.length,steps:s};if(a[m]<t)l=m+1;else r=m-1}return{i:-1,comparisons:s.length,steps:s}}},
 jump:{name:'Jump Search',complexity:'O(√n)',space:'O(1)',fn:(a,t)=>{let n=a.length,j=Math.max(1,Math.floor(Math.sqrt(n))),s=[],prev=0,next=j;while(prev<n&&a[Math.min(next,n)-1]<t){s.push(Math.min(next,n)-1);prev=next;next+=j;if(prev>=n)break}for(let i=prev;i<Math.min(next,n);i++){s.push(i);if(a[i]===t)return{i,comparisons:s.length,steps:s};if(a[i]>t)break}return{i:-1,comparisons:s.length,steps:s}}},
 interpolation:{name:'Interpolation Search',complexity:'O(log log n)*',space:'O(1)',fn:(a,t)=>{let l=0,r=a.length-1,s=[];while(l<=r&&t>=a[l]&&t<=a[r]){if(a[l]===a[r]){s.push(l);return{i:a[l]===t?l:-1,comparisons:s.length,steps:s}}let p=l+Math.floor((t-a[l])*(r-l)/(a[r]-a[l]));s.push(p);if(a[p]===t)return{i:p,comparisons:s.length,steps:s};if(a[p]<t)l=p+1;else r=p-1}return{i:-1,comparisons:s.length,steps:s}}}
}

const presets={small:Array.from({length:20},(_,i)=>(i+1)*5),medium:Array.from({length:40},(_,i)=>(i+1)*5),large:Array.from({length:80},(_,i)=>(i+1)*5)};
const randomData=n=>{let s=new Set();while(s.size<n)s.add(Math.floor(Math.random()*500)+1);return[...s].sort((a,b)=>a-b)};

function App(){
 const[data,setData]=useState(presets.small),[target,setTarget]=useState(50),[algorithm,setAlgorithm]=useState('binary'),[size,setSize]=useState('small'),[running,setRunning]=useState(false),[step,setStep]=useState(-1),[result,setResult]=useState(null),[tab,setTab]=useState('visualizer'),[history,setHistory]=useState([]);
 const alg=algorithms[algorithm], active=result?.steps?.[step]??-1;
 const reset=()=>{setRunning(false);setStep(-1);setResult(null)};
 const run=async()=>{reset();setRunning(true);let out=alg.fn(data,Number(target));setResult(out);setHistory(h=>[{name:alg.name,target:Number(target),comparisons:out.comparisons,found:out.i!==-1},...h].slice(0,8));for(let i=0;i<out.steps.length;i++){setStep(i);await new Promise(r=>setTimeout(r,algorithm==='linear'?150:280))}setRunning(false)};
 const generate=()=>{let n=size==='small'?20:size==='medium'?40:80;setData(randomData(n));reset()};
 const compare=useMemo(()=>Object.entries(algorithms).map(([key,a])=>{let t0=performance.now(),o=a.fn(data,Number(target)),ms=performance.now()-t0;return{key,name:a.name,c:o.comparisons,ms,found:o.i!==-1}}),[data,target]);
 useEffect(()=>{if(algorithm!=='linear')setData(d=>[...d].sort((a,b)=>a-b))},[algorithm]);
 return <div className="app"><header><div className="brand"><span className="logo"><Search/></span><div><b>Search<span>Lab</span></b><small>Algorithm Visualizer</small></div></div><nav><button className={tab==='visualizer'?'active':''} onClick={()=>setTab('visualizer')}><Zap/>Visualizer</button><button className={tab==='compare'?'active':''} onClick={()=>setTab('compare')}><BarChart3/>Compare</button><button className={tab==='learn'?'active':''} onClick={()=>setTab('learn')}><BookOpen/>Learn</button></nav></header>
 <main><section className="hero"><div><label>BCA FINAL YEAR PROJECT</label><h1>Search algorithms,<br/><em>made visual.</em></h1><p>Explore classic searching techniques step by step, compare their performance, and understand the difference between O(n), O(log n), and O(√n).</p></div><div className="hero-card"><div><Code2/></div><b>Interactive DSA Lab</b><span>Learn by running the algorithm.</span></div></section>
 {tab==='visualizer'&&<><section className="card controls"><div className="fields"><label>Algorithm<select value={algorithm} onChange={e=>{setAlgorithm(e.target.value);reset()}}>{Object.entries(algorithms).map(([k,a])=><option key={k} value={k}>{a.name}</option>)}</select></label><label>Target value<input type="number" value={target} onChange={e=>{setTarget(e.target.value);reset()}}/></label><label>Dataset<select value={size} onChange={e=>{let v=e.target.value;setSize(v);setData(v==='small'?presets.small:v==='medium'?presets.medium:presets.large);reset()}}><option value="small">20 elements</option><option value="medium">40 elements</option><option value="large">80 elements</option></select></label><div className="buttons"><button className="secondary" onClick={generate}><Shuffle/>Generate</button><button className="primary" disabled={running} onClick={run}><Play/>{running?'Running…':'Run Search'}</button></div></div><div className="meta"><span><Clock3/>Time: <b>{alg.complexity}</b></span><span><Database/>Space: <b>{alg.space}</b></span><span><Zap/>Sorted input: <b>{algorithm==='linear'?'No':'Yes'}</b></span></div></section>
 <section className="card"><div className="head"><div><label>LIVE VISUALIZATION</label><h2>Array search process</h2></div><button className="reset" onClick={reset}><RotateCcw/>Reset</button></div><div className="array">{data.map((v,i)=><div key={i} className={'cell '+(active===i?'active ':'')+(result?.i===i&&step>=result.steps.length-1?'found':'')}><b>{v}</b><small>{i}</small></div>)}</div><div className="legend"><span><i className="dot current"/>Current comparison</span><span><i className="dot found"/>Target found</span><span><i className="dot"/>Unchecked</span></div><div className={'result '+(result?(result.i!==-1?'ok':'bad'):'')} >{result?(result.i!==-1?<><CheckCircle2/><div><b>Target found!</b><span>{target} is at index {result.i} after {result.comparisons} comparison{result.comparisons!==1?'s':''}.</span></div></>:<><XCircle/><div><b>Target not found</b><span>The algorithm checked {result.comparisons} position{result.comparisons!==1?'s':''}.</span></div></>):<><Search/><div><b>Ready to search</b><span>Choose an algorithm and click Run Search.</span></div></>}</div></section>
 <section className="stats"><div><small>ARRAY SIZE</small><b>{data.length}</b><span>elements</span></div><div><small>ALGORITHM</small><b>{alg.name.replace(' Search','')}</b><span>{alg.complexity} time</span></div><div><small>COMPARISONS</small><b>{result?.comparisons??'—'}</b><span>operations</span></div><div><small>RESULT</small><b>{result?(result.i!==-1?'Found':'Not Found'):'—'}</b><span>{result?`index ${result.i}`:'run a search'}</span></div></section></>}
 {tab==='compare'&&<section className="card compare"><div className="head"><div><label>PERFORMANCE ANALYSIS</label><h2>Compare all algorithms</h2></div></div><p>All algorithms search the same sorted dataset and target.</p><table><thead><tr><th>Algorithm</th><th>Complexity</th><th>Comparisons</th><th>Measured time</th><th>Result</th></tr></thead><tbody>{compare.map(r=><tr key={r.key}><td><b>{r.name}</b></td><td>{algorithms[r.key].complexity}</td><td>{r.c}</td><td>{r.ms.toFixed(4)} ms</td><td className={r.found?'yes':'no'}>{r.found?'Found':'Not Found'}</td></tr>)}</tbody></table><div className="insight"><BarChart3/><span><b>What to observe:</b> Linear Search checks sequentially. Binary Search halves the range, Jump Search works in blocks, and Interpolation estimates the likely position.</span></div></section>}
 {tab==='learn'&&<section className="learn">{Object.entries(algorithms).map(([k,a])=><article key={k}><div className="num">{k==='linear'?'01':k==='binary'?'02':k==='jump'?'03':'04'}</div><h2>{a.name}</h2><p>{k==='linear'?'Checks each element sequentially.':k==='binary'?'Repeatedly halves a sorted search range.':k==='jump'?'Jumps by √n blocks and searches the matching block.':'Estimates the likely position from endpoint values.'}</p><b>Time:</b> {a.complexity}<br/><b>Space:</b> {a.space}</article>)}<article className="dark"><BookOpen/><h2>Final-year learning outcomes</h2><ul><li>Understand searching and complexity.</li><li>Visualize algorithm execution.</li><li>Compare theoretical and measured performance.</li><li>Build reusable React components.</li><li>Connect DSA concepts with frontend development.</li></ul></article></section>}
 {history.length>0&&tab==='visualizer'&&<section className="card history"><div className="head"><div><label>RECENT RUNS</label><h2>Search history</h2></div></div>{history.map((h,i)=><div className="history-row" key={i}><b>{h.name}</b><span>Target {h.target}</span><span>{h.comparisons} comparisons</span><span className={h.found?'yes':'no'}>{h.found?'Found':'Not found'}</span></div>)}</section>}
 </main><footer><b>SearchLab</b><span>Educational DSA project • React + Vite</span></footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
